-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("user.chatgpt")
require("user.open-ticket")
require("user.httpx")
require("user.run-java-test")
require("user.template-string-converter")
require("user.transforms.json-to-go")
require("user.transforms.json-to-java")
require("user.transforms.json-to-python")
require("user.transforms.json-to-ts")
require("user.transforms.json-to-yaml")
require("user.transforms.json-to-zod")
require("user.transforms.yaml-to-json")
